version: '3.8'
services:
  games-api:
    build: .
    container_name: games-backend
    restart: always
    ports:
      - "5269:3000"
    volumes:
      # 将容器内的 data 文件夹映射到宿主机的 data 文件夹
      # 这样哪怕容器删了重建，你的数据库 .sqlite 文件依然在！
      - ./data:/app/data
      - ./schema.sql:/app/schema.sql